name: schist
description: schist applies Stochastic Block Models to many task in analysis of single cell data. The main goal is to implement a robust way to identify cell clusters.
project_home: https://github.com/dawe/schist
documentation_home: https://schist.readthedocs.io
tutorials_home: https://schist.readthedocs.io/en/latest/tutorials.html
install:
  conda: conda-forge::schist
license: BSD-3-Clause
tags:
  - clustering
  - single-cell
publications:
  - 10.1186/s12859-021-04489-7
version: v0.8.1
authors:
  - dawe
  - leomorelli
test_command: |
  pytest conftest.py
