name: schist
description: |
  schist is a convenient wrapper for graph-tool applied to single cell data.
  It addresses the problem of clustering single cell data, by using Stochastic Block Models, a Bayesian approach to the identification of communities in graphs.
project_home: https://github.com/dawe/schist
documentation_home: https://schist.readthedocs.io
tutorials_home: https://schist.readthedocs.io/en/latest/tutorials.html
install:
  conda: conda-forge::schist
license: BSD-3-Clause
tags:
  - clustering
  - single-cell
publications:
  - 10.1186/s12859-021-04489-7
version: v0.8.1
authors:
  - dawe
  - leomorelli
test_command: |
  pytest conftest.py
